config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'homes#top'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true, length: {maximum: 50}
  validates :body, presence: true, length: {maximum:300}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all.order(id: :asc)
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to @book
    else
      @books = Book.all.order(id: :asc)
      flash[:notice] = "error"
      render("books/index")
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to @book
    else
      flash[:notice] = "error"
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model: @book, local:true do |f| %>
<% if @book.errors.any? %>
    <%= @book.errors.count %> error
    <% @book.errors.full_messages.each do |msg| %>
      <ul><li><%= msg %></li></ul>
    <% end %>
  <% end %>
  
  <div class="field">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body, "Body" %>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
  <%= f.submit 'Update Book' %>
  </div>
<% end %>
<%= link_to 'Show', book_path(@book) %>
|
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", book %></td>
        <td><%= link_to "Edit", edit_book_path(book) %></td>
        <td><%= link_to "Destroy", book, method: :delete, "data-confirm" => "Do you really want to delete this post" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>New Book</h2>
<%= form_with model: @book, local: true do |f| %>
  <% if @book.errors.any? %>
    <%= @book.errors.count %> error
    <% @book.errors.full_messages.each do |msg| %>
      <ul><li><%= msg %></li></ul>
    <% end %>
  <% end %>
  <div class="field">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body, "Body" %>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Book' %>
  </div>
<% end %>

app/views/books/show.html.erb
<h1>Show</h1>

<p>
    <strong>Title: </strong>
    <%= @book.title %>
</p>
<p>
    <strong>Body: </strong>
    <%= @book.body %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %>
|
<%= link_to 'Back', books_path %>

app/views/homes/top.html.erb
<h1>
  ようこそ<storng>Bookers</storng>へ！
</h1>
<p>
  <storng>Bookers</storng>では、さまざまな書籍に関するあなたの意見や
</p>  
<p>
  印象を共有し交換することできます
</p>
<p>
  <%= link_to 'Start', books_path %>
</p>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <p style="color: <%= flash_type == 'notice' ? 'green' : 'red' %>;"><%= msg %></p>
  <hr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    
    <%= yield %>
  </body>
</html>